# Generated by Django 4.2.10 on 2024-03-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='quantity',
        ),
    ]
