# Generated by Django 4.2.10 on 2024-03-03 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='account_no',
        ),
    ]
